### ISSUE TITLE
Linux on PSP

### ISSUE THREAD

**Issue by Mis012** [PSPReverse/PSPTool#10]
Hi,
I assume you have little interest in enabling Linux to run *on* the PSP, but would you be open to creating documentation of the hw aspects of the arm core that could aid in that task in case someone picks it up?
I think there's a lot of potential in this, even if it's likely something noone ever envisioned.
The ideal end result would be having x86 architectural chroot, but running Linux on the PSP without caring about the x86 cores would already be a great achievement :)

**Comment by RobertBuhren** [comment]
The PSP has only 256KB of local SRAM (Zen1) . While it has access to the DRAM, I don't think it can be used a "normal" RAM. 

I don't think it is desirable/feasible to run Linux on the PSP. However, a custom and open-source OS would be nice.
