### ISSUE TITLE
Request: Release recent fixes to PyPi (#29 & suggested fix for #30)

### ISSUE THREAD

**Issue by aGrimRepoMan** [PSPReverse/PSPTool#34]
Hi,

Steps:
1. "pip install psptool", then "pip install ipython".
2.  Run psptool on this X470 BIOS file: [https://download.gigabyte.com/FileList/BIOS/mb_bios_x470-aorus-ultra-gaming_f61.zip?v=cdfa827c3cc8778e89c60c410b5bef51](url)

Result:   I encountered the same problems as described by #30 and then #29.

If I understand correctly, #30 has a suggested fix, while #29 has a fix completed by project team. Once I manually apply these, I can succesfully read the BIOS file.

My request:  Is it possible to release these 2 fixes to PyPi so they are included automatically for new users who do a simple "pip install psptool"?

Thanks for considering this.

**Comment by cwerling** [comment]
Thanks for suggesting this, will do a release shortly.

X470 works for me, X570 though has still issues yet to be addressed.

**Comment by cwerling** [comment]
Release 2.3 done. You can now install the latest version from PyPI:

```
pip3 install psptool
```

**Comment by aGrimRepoMan** [comment]
Thanks Christian - much appreciated.
