### ISSUE TITLE
Could this be used as me_cleaner for AMD PSP?

### ISSUE THREAD

**Issue by DsSoft-Byte** [PSPReverse/PSPTool#56]
Hi there, and also thanks for your helpful research. All my computers at home are Pre-IME Intel computers and Other Skylake+ Systems sanitized with corna's intel me_cleaner. I have a system based on Gigabyte's B550 Aorus V2 Elite. Board Revision V1.2, PSPTool output is attached, i ran it on my currently installed BIOS Image. I wonder (as this is a question not an issue) if this tool can be used to produce a sanitized BIOS that i could install via SPI/SOIC Clip (As Quick Flash check would probably fail)? I would be extremely happy and willing to pay a coffee if one of you could guide me in the right direction. Cheers! (Also including my Firmware directly from Gigabyte i ran the tool on and that my machine is running.
[PSPTool-Output.txt](https://github.com/PSPReverse/PSPTool/files/13802310/PSPTool-Output.txt)

[B550AEV2.zip](https://github.com/PSPReverse/PSPTool/files/13802312/B550AEV2.zip)

**Comment by Ragebone** [comment]
Hi there.
As was discussed in a recent issue on here, there is no "ME Cleaner" like functionality right now.
There also seems to be no need for such functionality.

Issue for reference:
https://github.com/PSPReverse/PSPTool/issues/54

As far as i am concerned, there is nothing for you to do around the PSP with your Giglebyte B550 system.
Except of course Giglebytes UEFI issues.
