### ISSUE TITLE
"zlib.error: Error -5 while decompressing data: incomplete or truncated stream" from specific BIOS

### ISSUE THREAD

**Issue by thehans** [PSPReverse/PSPTool#8]
I was checking out your tool and trying it on all the previous versions of my motherboard's BIOS, and I got an error for one specific version:
```
$ psptool -Xunk PRIME-B450-PLUS-ASUS-0809.CAP
Traceback (most recent call last):
  File "/usr/local/bin/psptool", line 11, in <module>
    load_entry_point('psptool==2.0', 'console_scripts', 'psptool')()
  File "/usr/local/lib/python3.6/dist-packages/psptool-2.0-py3.6.egg/psptool/__main__.py", line 119, in main
  File "/usr/local/lib/python3.6/dist-packages/psptool-2.0-py3.6.egg/psptool/entry.py", line 308, in get_decompressed
  File "/usr/local/lib/python3.6/dist-packages/psptool-2.0-py3.6.egg/psptool/entry.py", line 314, in get_decompressed_body
  File "/usr/local/lib/python3.6/dist-packages/psptool-2.0-py3.6.egg/psptool/utils.py", line 190, in zlib_decompress
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
```

The BIOS download page is here
https://www.asus.com/us/Motherboards/PRIME-B450-PLUS/HelpDesk_BIOS/
And the particular file is here:
https://dlcdnets.asus.com/pub/ASUS/mb/SocketAM4/PRIME_B450-PLUS/PRIME-B450-PLUS-ASUS-0809.zip

I tried re-downloading and extracting, and the .CAP binaries matched, so I don't think it is a corrupt download.

**Comment by RobertBuhren** [comment]
Sorry for the late reply. I believe there is something wrong with some of the entries of that image. Looking at the header of the entries that fail to decompress, I can see that the header says they're compressed (offset 0x48). However, the body data does not look compressed at all.

I have added a warning to PSPtool that allows to continue extracting entries regardless of a failed zlib decompression. If an entry can't be decompressed, the orginal bytes are extracted instead.

I'll keep this issue open for now, in case we stumble on other UEFI images with the same weird behavior. 

Regards,

Robret

**Comment by thehans** [comment]
Thanks, I looked at the output from this latest change in a hex editor and it seems that there is still compressed data (magic bytes 78 DA), but it starts at 0x100 offset into what was extracted (eg file: `0x1100064_0.0.10.0`)

I have mostly moved on from being interested in this BIOS, since I've replaced the board with a better model.  But still willing to test out stuff if there's anything I can help with to make the tool more robust.

**Comment by thehans** [comment]
BTW not sure what it means but I see *two* files in output that start with "0x1100064"
`0x1100064_0.0.10.0` mentioned above
and
`0x1100064_0.0.18.5` which i guess is the part that's not compressed?

**Comment by RobertBuhren** [comment]
I just pushed some more fixes to psptool. The zlib decompression now works with this image too.

Thanks for reporting this issue.
